### ISSUE TITLE
Ingestor should delete deleted items from the elasticsearch index

### ISSUE THREAD

**Issue by alicefuzier** [wellcometrust/platform#1283]
* Delete deleted items
* Suppress suppressed items

**Comment by alexwlchan** [comment]
Slight change of plan: rather than deleting records entirely, we're going to write an empty record into Elasticsearch with "visibility: false". This:

* Simplifies the implementation
* Allows the API to return a 410 when we've minted an ID for a record but deleted it later

Longer-term, this makes #1425 more pressing.
