### ISSUE TITLE
Do we need to support searching on variants of the Sierra system number?

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1651]
The proposal in #1639 is that we store and present two forms of the Sierra ID:

* Without a prefix or check digit, e.g. `1234567`
* With a prefix and check digit, e.g. `b1234567x`

The Sierra manual says:

> When searching for a record number, if you don't know the check digit, you can substitute the
> character **a** for the check digit. For example, you could enter [.b1024364] as .b1024364a.

Elasticsearch won't know about this variant of the ID. Should we include it as an invisible identifier – indexed for search, but not visible to the user? Is this wildcard ever exposed to users? Is it supported in the current library search?

**Comment by alexwlchan** [comment]
Similarly, record numbers are often prefixed with a `.`, e.g. `.b1234567x`. Do we need to support that variant as well?

**Comment by pollecuttn** [comment]
Re variant ID: Well ... the wildcard isn't exposed to the user as such but if the user knows about it they can search by it.

This works - no check digit: http://catalogue.wellcomelibrary.org/record=b1766666
This works - with 'a' instead of the check digit: http://catalogue.wellcomelibrary.org/record=b1766666a
This doesn't - with check digit: http://catalogue.wellcomelibrary.org/record=b17666661
