### ISSUE TITLE
Analysis of Miro images based on specific metadata

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#1838]
- [x] Identify all images on /works supplied by Science Museum Brought to Life (and possibly other Science Museum photos). Could do this via MIRO metadata; 
- [x] alternatively comparing images against the Science Museum collections search might result in a larger set – these are likely to go into Tandem Vault as a next step, but I’m not sure of the extent/coverage.

- [x] Extract metadata for images on /works which do not have associated ‘b’ numbers, grouping them according to the following groups of MIRO ids:
  - M prefixes
  - L prefixes
  - V prefixes
  - Other prefixes

- [x] Parse data from B3. to regroup according to alternative identifiers – this will be tricky because of data entry inconsistencies and changes in referencing practice over many years but I can help with this. 
Find some sort of order in the `miro-library-reference` for records which don't have `sierra-image-number`s

- [x] Extract and normalise MIRO ids referenced in Calm records (see spreadsheet – I’ll have to pull another export for those rows where column C is currently blank – there must be references to Wellcome Images in other field(s) which I’d failed to spot. Thinking about this further, I’m going to do this before sending you a revised set of data. Will try to do this later this afternoon, if not next week).To make this workable from our end, it would be helpful to end up with an array of ids against each row (which represents a single record in Calm).

- [x] Compare the two lists of MIRO ids from tasks B3 and B5 in order to generate two new lists (a) MIRO ids of images on /works which are not in Calm and (b) MIRO ids in Calm which do not have images on /works

- [x] Provide samples of metadata for the first and last 10 records in MIRO (not all of these are on /works) for the following sequences, for possible re-use as collections catalogue data – I suspect the quality is poor, and I’m not sure of the start and end points of the MIRO data, so this is to begin to investigate both aspects:
  - M
  - L
  - A
  - N

**Comment by harrisonpim** [comment]
- [ ] Identify all images on /works supplied by Science Museum Brought to Life (and possibly other Science Museum photos). Could do this via MIRO metadata; alternatively comparing images against the Science Museum collections search might result in a larger set – these are likely to go into Tandem Vault as a next step, but I’m not sure of the extent/coverage.

- [ ] Extract metadata for images on /works which do not have associated ‘b’ numbers, grouping them according to the following groups of MIRO ids:
  - M prefixes
  - L prefixes
  - V prefixes
  - Other prefixes

- [ ] Parse data from B3. to regroup according to alternative identifiers – this will be tricky because of data entry inconsistencies and changes in referencing practice over many years but I can help with this.

- [x] Extract and normalise MIRO ids referenced in Calm records (see spreadsheet – I’ll have to pull another export for those rows where column C is currently blank – there must be references to Wellcome Images in other field(s) which I’d failed to spot. Thinking about this further, I’m going to do this before sending you a revised set of data. Will try to do this later this afternoon, if not next week).To make this workable from our end, it would be helpful to end up with an array of ids against each row (which represents a single record in Calm).

- [ ] Compare the two lists of MIRO ids from tasks B3 and B5 in order to generate two new lists (a) MIRO ids of images on /works which are not in Calm and (b) MIRO ids in Calm which do not have images on /works

- [ ] Provide samples of metadata for the first and last 10 records in MIRO (not all of these are on /works) for the following sequences, for possible re-use as collections catalogue data – I suspect the quality is poor, and I’m not sure of the start and end points of the MIRO data, so this is to begin to investigate both aspects:
  - M
  - L
  - A
  - N
