### ISSUE TITLE
Determine migration plan for existing digitised content

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#2789]

**Comment by tomcrane** [comment]
* `(Done)`  Running test environment using new storage service, DDS and DLCS config, and METS schema
* `(Pending)` configure required permissions for bagger to read all its source locations (Preservica and DDS buckets) 
* `2018-11-15` Re-bag a new set of 500 plus b22454408 
* `2018-11-15` bag the [special test b numbers](https://github.com/wellcometrust/platform/blob/master/archive/bagger/reference_data/b_numbers.txt)
* `2018-11-16` Run bulk DLCS migration tool. This creates equivalent rows in DLCS space 5 for all existing DLCS assets in space 2, registered with the new origin [1]. Thumbnails are duplicated. Access control configuration (where applicable) is replicated. 
* `2018-11-16` Test the 500 and the special b numbers and fix any issues:
  * Selectively, run some through the Goobi-DDS sync
  * Run others through the manual sync processes in the dashboard
  * When satisfied, re-run them all through the Goobi-DDS flow using the tool below
* `2018-11-nn` Do a fresh sync of METS to AWS bucket (save the timestamp when this happens for later use)
* `2018-11-nn` export the list of b numbers at that point (will be useful for later reconciliation) - a simple newline separated text file is fine ([bnums.sh](https://github.com/wellcometrust/platform/blob/master/archive/bagger/local_executables_examples/bnums.sh) will do this).
* `2018-11-nn` Bag **everything** in that list (don't know how long that will take) (enqueue messages)
* `2018-12-nn` run that list of bnumbers through the goobi-DDS workflow call (see utilities, next). This will create the cached packages, search and annotation list objects. These are portable - the same cached binary files generated in the test environment can be copied to the live environment on go-live day (see below). However, they are not portable across old and new archive storage, as every identifier is different! So we need to have them all ready for the big day.

Utilities used:

1. Read list of b numbers and call DDS Goobi workflow for each (very simple, Python or .NET - but needs to be throttled and controllable). Used to populate cached items and clean up any DLCS sync missed
2. Patch live DDS DB with additional `FirstFileStorageIdentifier` field it will need after switch (this needs to be .NET to take advantage of all the existing client code, Python version would take much longer to write). This adds in the value populated during the Goobi-DDS workflow on test to the live DB. 

Simplify the **catch up** process as much as possible:
For any b number that has changed since _some date_,
  * Bag it
  * Ingest to archive storage 
  * call Goobi-DDS workflow for each b number
  * Run live DB patcher to populate live DB

Now it depends on timing. 

We can't deploy the new configuration to the live environment until Goobi is bagging to the archive service and calling the DDS afterwards.

Pause ingest until Goobi can bag too? Or keep feeding Goobi to the existing environment?
If the latter, we should periodically run the **catch up** so there's not too much catching up to do on switchover day. Want to keep any downtime to a minimum.

### In anticipation of imminent switchover day

* Stop all ingest activity
* Run a final catch up process as described above
* make sure there's enough disk space on the cache share
* Prepare build configurations for DDS, Dashboard, Background Jobs and be ready to deploy them (via TeamCity)

### Switchover day

* Put up a notice warning of possible disruption to digital objects (don't need to turn them off)
* Start copying cached packages, search and annotation files from test to live environment
* Deploy
* Verify Digital Delivery is working as expected
* Restart workflow
* Monitor new items through workflow

[1] `https://s3-eu-west-1.amazonaws.com/wellcomecollection-storage-access/digitised/{0}/data/objects/{1}` 
_Running this is a major time and cost saving. We could populate Space 5 by running every b number through the current workflow once bagged, but that would involve $1000s of unnecessary compute resource and data transfer._

**Comment by tomcrane** [comment]
The two utils mentioned above have now been written and tested.

**Comment by tomcrane** [comment]
Possible way to track and report on this;

Create a DynamoDB (or something table-ish) table for items with attributes:

**Identifier** (b number)
Table is initially populated by creating rows for every b number yielded from the synced METS bucket

**Bag date** (timestamp, may be null)
When the b number was bagged.

**Ingest started** (timestamp, may be null)
When (if) the ingest was triggered

**Ingest id** 
The id supplied by the ingest service - the most recent for this item
(store a list of all ingest ids as well?)

**Ingest status**
Latest known ingest status for this ingest

(store ingest success date? is that useful?)

**DDS called** timestamp
records the fact that the DDS has been notified (simulating Goobi's call)

**Package** (timestamp? bool?)
The DDS has built a package for this item and cached it

**Text** (timestamp? bool? may be N/A)
The DDS has built the text source(s) for this b number

[optional, probably not worth doing, can be random manual testing]

**Manifest** (HTTP status?)
The DDS is correctly serving a IIIF manifest (or collection) for this item

**Item page**
The web site is correctly serving the item page for this item
