### ISSUE TITLE
Support Archivematica updates to storage service

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#2836]
In order to provide updates to bags already ingested.
We need to support Archivematica "hooks" to:

- [X] Ingest into storage service

- Download from storage service 
  - [X] retrieve manifest from storage service
  - [x] get bag!

_Archivematica expects "symmetric" upload/download types for transfers_

- [x] Modify in Archivematica (currently errors as bag seems incorrect)?
- [x] Reupload
  - [x] Ensure version number of bag is retrieved and stored against the `Package`.
  - [x] Ensure 'update' method on API is called when reuploading
  - [x] Ensure version number is used to retrieve correct version from Wellcome storage
- [x] Test with other types of Archivematica reingest (metadata, partial)
- [x] Test reingesting package a second time
- [x] Investigate why a package's "Date stored" doesn't seem to be updated in Archival Storage after reingest

**Comment by kenoir** [comment]
Currently there is an issue where Archivematica will not accept bags downloaded from the storage service in an unpacked format.

Talking with @helenst we worked out the following remedies:
- Ascertain whether Archivematica can be easily modified to handle unpacked bags as a data source
  - If yes: do that!
  - If no: 
    - Ticket issue with Archivematica devs 
    - Locally download and `tar.gz` a bag after download

**Comment by kenoir** [comment]
Ping @jtweed ^

**Comment by helenst** [comment]
Looking into how we / archivematica do the .tar.gz stuff

We upload as a gzipped file. In order for the metadata on the Archivematica-generated AIPs to be correctly generated, the `current_path` attribute of the AIP package object in the database must be suffixed '.gz' (if it is not, it ends up as a .7z during the reingest and subsequently rejected by the Wellcome storage service)

If I set the path to .gz, a couple of things happen:

1. the AIP download becomes named NAME-uuid.tar.gz.tar (rather than NAME-uuid.tar) (although the file itself is still a simple tarball)
2. the reingest transfer is named NAME-uuid.tar.gz rather than NAME

This appears to be because the download is in the format of a directory, but given the name of a compressed file. I'm currently looking into what happens when we gzip up the directory after downloading it from S3.

**Comment by helenst** [comment]
The .tar.gz wrapped inside a tarball seems to happen with regular local storage as well. In both cases it is fine on the first download. I'm not going to look into it further at this point as I don't think it's specific to the Wellcome plugin.

**Comment by helenst** [comment]
Next step is to examine how the reingest is working with the plugin as it currently stands - is it doing what we expect, using versions correctly, etc?

**Comment by helenst** [comment]
It now supports the versioning API. Reingested packages are stored on the back end as subsequent versions. Repeated reingests of a package appear to work.
