### ISSUE TITLE
 Add success/failure metrics to all Storage service apps

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#3279]
In order to identify success & failure effectively and at scale all services should report the status of operation on individual SQS messages (each message being a parcel of work for that service).  

API services should record 200/non-200 responses.

Workers:
- [ ] Archivist
- [ ] Ingest Service
- [ ] Notifier Service
- [ ] Bags Service

APIs:
- ~Ingest API~ (moved to #3423)
- ~Bags API~ (moved to #3423)

**Comment by tomcrane** [comment]
@kenoir -

Where would they be reporting this to? This sounds like a more formal and permanent version of the dynamoDB table we're using to collate status of migration activity per b number. The difference here is that the services themselves would record what they do, rather than an external updater populating the table by examining the status of the various expected outputs. 

We still need the latter, during migration, as it does things that probably wouldn't be required later. But the updater could also look at this source of data in building its picture.

**Comment by alexwlchan** [comment]
I'm going to look at getting metrics from the HTTP apps
