### ISSUE TITLE
Storage ingest issues

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#3420]
- [x] HEADOBJECT failures: https://github.com/wellcometrust/platform/pull/3413
- [x] Archivematica directory issue https://github.com/wellcometrust/platform/issues/3385
- [x] bag-info.txt: Optional source-organisation https://github.com/wellcometrust/platform/pull/3427
- [x] The bagger is still failing some bags because of capitalisation problems (https://github.com/wellcometrust/platform/issues/3420#issuecomment-463199205)

**Comment by mklander** [comment]
The bagger is still failing some bags because of capitalisation problems, now with 'b' not 'x'.  For example `b1823561x` has files stored in S3 with capital 'B's and 'X's, such as B1823561X_0001.xml (https://s3-eu-west-1.amazonaws.com/wellcomecollection-assets-workingstorage/mets/x/1/6/5/b1823561x_alto/B1823561X_0001.xml)
