### ISSUE TITLE
Upload to S3 automatically triggers Archivematica transfer

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3555]
Uploading a zip file should automatically trigger a transfer in Archivematica.

We should hopefully be able to use an S3 event stream to somehow trigger the Archivematica automation tools.

**Comment by helenst** [comment]
So far I have a working lambda that will respond to an object added to a bucket, and communicate with the storage service and archivematica APIs to start and approve a transfer.

The lambda operates as follows:

* Query the storage service API to find the right location that matches the bucket and key and get its uuid
* POST to the start_transfer API to initiate the transfer (using the location uuid and the S3 key)
* Poll the unapproved transfer API to detect when the transfer is ready for approval
* POST to the approve API to approve the transfer

This doesn't actually use automation-tools or amclient - just requests lib (a version of which is provided on the lambda platform)

Still TODO:
- [ ] see if we can get it to start the transfer using the automated workflow
- [ ] Get it working end to end with s3 triggers (rather than just the lambda test feature)
- [ ] Get everything into terraform
- [ ] Use environment variables for API settings, keys etc.
