### ISSUE TITLE
Remove prefix as a separate property on contributors

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3591]
Currently we're splitting subfield `c` into a separate `prefix` property on contributors.

We should remove this property and all contributor labels (100, 110, 700 and 710) should be a concatenation of subfields `a`, `b`, `c` and `t`.

See the following for more complex person and organisation examples:

https://api.wellcomecollection.org/catalogue/v2/works/fwquzvcf?include=contributors,identifiers
http://search.wellcomelibrary.org/iii/encore/record/C__Rb1310641?lang=eng

https://api.wellcomecollection.org/catalogue/v2/works/g829snzf?include=contributors,identifiers
https://search.wellcomelibrary.org/iii/encore/record/C__Rb3001164?lang=eng

**Comment by jamesgorrie** [comment]
@jtweed to be clear from the slack messages:

* Currently we split a person into
  * `a => label`
  * `c => prefix`
  * `b => numeration`

We do this for both `100` and `700`.

We also extract subfield `t` from `700`. If this exists we create an `Agent` rather than a `Person`. We omit `t` from anywhere in the data.

What we would like to do is join subfields `a`, `b`, `c` into the label, and use subfield `t` in the same way?

**Comment by jtweed** [comment]
All correct, except we should add subfield `t` if it exists.

**Comment by jamesgorrie** [comment]
`ǂt` being the title of the work?

We currently do nothing with it except differentiate between `Agent` and `Person` - out of interest, as the code doesn't say, what's the reason for that split?

**Comment by jamesgorrie** [comment]
For reference, we are also adding subfield `d` as per #3592

**Comment by jamesgorrie** [comment]
Example of the change in action:
https://search.wellcomelibrary.org/iii/encore/record/C__Rb1216128?lang=eng&marcData=Y
https://api-stage.wellcomecollection.org/catalogue/v2/works
https://api.wellcomecollection.org/catalogue/v2/works

(These links will go out of date as an example over time)
