### ISSUE TITLE
Finalise Archivematica configuration

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3679]
- Remove unused storage locations
- Set up locations with `born-digital` relative path
- Take WSS `space` from relative path
- Remove default and automated pipelines
- Add `born-digital` pipeline configured as per RFC to use new spaces
- Use `born-digital` pipeline for packages uploaded to S3

**Comment by helenst** [comment]
Archivematica coding tasks:
- [ ] Use `Location.relative_path` as the final location of the AIP (e.g. `born-digital`), rather than the temporary upload location. The temporary upload location can be constructed from this. (e.g. `/archivematica/aips/born-digital`)
- [ ] Change the S3 transfer lambda so the upload path maps to a processing config

Infrastructure tasks:
- [ ] Remove default and automated pipelines
- [ ] Remove unused storage locations
- [ ] Add born-digital workflow
- [ ] Set up born-digital `Location`
- [ ] Create S3 transfer location for born-digital

**Comment by helenst** [comment]
Some difficulty with with running custom workflows - I have a fix but running it by the Artefactual team to make sure it's the right thing to do: https://github.com/archivematica/Issues/issues/771

**Comment by helenst** [comment]
The default and automated processing configurations are built in to Archivematica and can't be deleted. Maybe there's some way we can set them up sensibly (especially as there's no way to select a processing config from the UI so dashboard users will get the default workflow)

**Comment by ross-spencer** [comment]
Following along at home, this might be of interest to y'all: 

* https://github.com/artefactual/archivematica/pull/1222
* And that's related to: https://github.com/artefactual/archivematica/issues/800

I think there are a few of us who would agree it would be a small superpower for Archivematica to be able to do this from the transfer browser via drop-down. There's certainly a lot more flexibility to be found from different processing configs beyond the initial two. You might have some luck just using the API endpoint on its [own too](https://wiki.archivematica.org/Archivematica_API#Package).

**Comment by helenst** [comment]
PR https://github.com/artefactual/archivematica/pull/1446

**Comment by helenst** [comment]
@ross-spencer Yeah ultimately we're going to be using this on the API endpoint. I've been testing it with the javascript hack, although of course it would be nice to be able to select!

**Comment by helenst** [comment]
Removed local transfer source and AIP storage - the others are (as far as I can tell) necessary, except possibly the DIP storage since we are not generating DIPs.
