### ISSUE TITLE
Bags API: the "locations" block refers to "bucket"

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#3837]
That's going to get clunky when we have Azure blob storage – “bucket” is a very S3 specific term.

Do we want to change that?

**Comment by jtweed** [comment]
So that’s exactly what I thought, but it turns out it’s also the term used by Google Cloud Storage.

Azure uses the term `container`. That’s what the RFC originally said, as I thought it was more generic. But then I swapped to `bucket`.

No strong opinion either way, so happy to change this now with the other location changes if you do.
