### ISSUE TITLE
Add thumbnail for all digitised items

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3945]

**Comment by alicefuzier** [comment]
The thumbnail URL is something like `https://dlcs.io/iiif-img/wellcome/${space}/${filename}/full/${width},/0/default.jpg` where
 - The `space` will always have value 5 for everything coming from the storage service
- `width` will be one of the precomputed sizes in [info.json](https://dlcs.io/iiif-img/wellcome/5/b30246039_0001.jp2/info.json) (244 or 122 in this case)
- `filename` is in the METS XML in the `fileSec` section i.e `b30246039_0001.jp2` with a `fileSec` like this:
```
<mets:fileSec>
    <mets:fileGrp USE="OBJECTS">
      <mets:file ID="FILE_0001_OBJECTS" MIMETYPE="image/jp2">
        <mets:FLocat LOCTYPE="URL" xlink:href="objects/b30246039_0001.jp2" />
      </mets:file>
...
    </mets:fileGrp>
</mets:fileSec>
```
NOTE: 
 - Strip "objects/" from the link
 - Double check if we can just take the first file in `fileSec` or if we have to look into ` <mets:structMap TYPE="LOGICAL">` and ` <mets:structMap TYPE="PHYSICAL">` first to choose the thumbnail image

**Comment by alicefuzier** [comment]
Just wondering about the frontend: looking [here](https://github.com/wellcometrust/catalogue/blob/master/pipeline/transformer/transformer_miro/src/main/scala/uk/ac/wellcome/platform/transformer/miro/transformers/MiroImageApiURL.scala#L8), the Miro thumbnails have a fixed width of 300px.
If we want to use the precomputed thumbnails from dlcs though, they seem to have fixed height, not fixed width. 

Not understanding anything about frontend development, does that mean that some adjustments are needed in the frontend? If we have a mixture of Miro thumbnails and DLCS thumbnails would that cause issues?
 @gestchild @davidpmccormick

**Comment by tomcrane** [comment]
Hey @alicefuzier - not sure if this will help but there are some shortcuts you can take with this if you know (as you do in this case) the thumbnail size settings that the DLCS uses. For example, if you want a thumbnail confined to a 100x100 box, you don't need to know the actual image dimensions.

For example, the DDS has this service:
https://wellcomelibrary.org/service/workthumb/b19953021/0

Which redirects to the DLCS thumbnail URL of the first image of the 0th manifestation:
https://dlcs.io/thumbs/wellcome/5/b19953021_0001.jp2/full/!100,100/0/default.jpg

The full implementation of this service in the DDS is:

```
  public ActionResult WorkThumb(string bNumber, int manifestation)
  {
      using (var ctx = new DdsContext())
      {
          var flatManifestation =
              ctx.FlatManifestations.FirstOrDefault(
                  fm => fm.PackageIdentifier == bNumber && fm.Manifestation == manifestation);
          if (flatManifestation == null)
          {
              return HttpNotFound();
          }
          if (flatManifestation.FirstFileStorageIdentifier.HasText())
          {
              var dlcsUrl = simpleThumbTemplate
                  .Replace("{name}", flatManifestation.FirstFileStorageIdentifier)
                  .Replace("{size}", "!100,100");
              return RedirectPermanent(dlcsUrl);
          }
      }
      return HttpNotFound();
  }
```

where the const `simpleThumbTemplate` is `"https://dlcs.io/thumbs/wellcome/5/{name}/full/{size}/0/default.jpg"`

The DDS knows the first identifier for each manifestation (b19953021_0001.jp2 in this case). It could (but doesn't presently) know a "preferred" identifier to use for thumbnails, for example the title page if identified in METS.

The DDS/DLCS has a _thumbnailPolicy_ which makes optimised thumbs - these don't involve an image server, they are proxied direct from precomputed thumbs in S3, so they are suitable for fast thumbnails.

**Comment by tomcrane** [comment]
If you just use /,{height}/ you may not get an optimised thumbnail - only if height is the longer dimension (therefore setting the bounding box). Whereas /!{nn},{nn}/ says "confine the image to box nn x nn".

The DLCS returns an HTTP Header `derivative: true` when the image has been proxied from S3 rather than via an image server invocation, for verifying that you're asking for optimised thumbs.

**Comment by alicefuzier** [comment]
Ah nice, thanks @tomcrane , didn't know that. Sounds like the bounded box is what we want.
Another question: should we make the request to https://dlcs.io/thumbs or https://dlcs.io/iiif-img? Is there any difference? I stole the second url from the images resolved in the universal viewer

**Comment by tomcrane** [comment]
They will both return the same proxied image as an optimisation, but the thumbs is better as that service is explicitly only offering the 4 sizes - it's more obvious to someone delving into the image requests that this service is for thumbs only. iiif-img will return any sizes, thumbs only the listed sizes.

I wouldn't use what the UV is doing as a guide as it's not taking advantage of any `sizes` optimisations in IIIF Image API.

**Comment by warrd** [comment]
Thanks @tomcrane, very helpful.

Looking at the code snippet u posted above, that is tied to the `100,100` thumbnail. If we wanted one of the other precomputed ones, I assume this means we have to parse the XML ourselves to get the filename etc (as @alicefuzier detailed above)? Is it safe to assume the first file defined in the XML is the title page, or should we look up the `structMap`in the XML to find that out?

**Comment by tomcrane** [comment]
Yes, the DDS is only storing the first file per _manifestation_ (so you could offer three thumbs for a three vol work).

> Is it safe to assume the first file defined in the XML is the title page..

No - the first file will rarely be the title page, it will often be a featureless buckram binding or similar. 

For printed books, Monograph etc., the METS structural metadata usually identifies front cover, back cover, title page and table of contents. This is used by the DDS to generate navigation via IIIF Ranges in the manifest, from the structMap as you say.

It's also used by the DDS in a more subtle way. For many printed books, the order the images are sequenced in the IIIF Manifest is not the same as they appear in raw form in the METS, which usually reflects the photography order rather than the logical paging of a book. For example the back cover is often the second image in the METS, but you wouldn't want that in a viewing experience.

The DDS does some work to order the images to make a sensible reading experience. The algorithm goes something like...

        /// Move the back cover to the end of the sequence
        /// Identify a suitable anchor point that MUST be recto (usually title page)
        /// If this isn't recto in the paging sequence, try to re-flow pages before it

In https://wellcomelibrary.org/iiif/b18035978/manifest you can see that b18035978_0002.JP2 has been shifted to the end of the sequence.
