### ISSUE TITLE
Add access conditions from METS to digital locations

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3946]
We need to extend locations to include data on access conditions. This sits alongside the current model for licenses, as another kind of restriction on use.

Access conditions should be a list, as it is possible for the field to repeat in Sierra and also for archives to be closed and restricted.

For digital locations, a single access condition should be created from `<mods:accessCondition type="status">` and, if present, `<mods:accessCondition type="usage">`.

It should look like the following:

```
accessConditions: [
    {
        "type": "AccessCondition",
        "terms": "Usage goes here",
        "status": {
            "type": "AccessStatus",
            "id": "open",
            "label": "Open"
        }
    }
]
```

`AccessStatus` should be considered similar to `Licence` and the following statuses should be created:

- Open
- Open with Advisory
- Restricted
- Closed
- Licensed Resources

The mapping from access status in the METS to the above statuses is as follows:

- Open -> Open
- Requires registration -> Open with Advisory
- Restricted -> Restricted
- Clinical images -> Restricted
- Closed -> Closed
- In copyright -> Licensed Resources

**Comment by jamesgorrie** [comment]
@jtweed just because I'm not 100% sure, what is "Access conditions"?

**Comment by jamesgorrie** [comment]
@pollecuttn @jtweed could you give us an plain text example of what this might be?

**Comment by tomcrane** [comment]
I can show you these in METS and what they mean for functionality.
@pollecuttn has a very ancient spreadsheet that explain these.

Current values expected to be seen in METS are:

- Open
- Requires registration
- Clinical images
- Restricted files
- Closed

The second one is misleading, as the eventual behaviour decided on for those was that the user has to accept terms and conditions for viewing, but doesn't have to say who they are - they don't need to register or log in. A better name for that one would be "Clickthrough".

Here's an example, if you're on the Wellcome network:
http://wt-havana:88/Dash/Manifestation/b20035421

Compare with:
http://wt-havana:88/Dash/Manifestation/b31404807

Access Conditions do not belong to the work as a whole, but to structures within the work.
Usually, this is the root structure and therefore the access condition applies to every image (or video) in the work.
Sometimes, an archive item might be mostly "Requires Registration" (i.e., clickthrough), but a few images have been restricted (maybe they contain sensitive information). In this scenario, there will be a subsection (structure) in the METS that defines an overriding access condition for its members. Like file permissions on subfolders.

In the views above, it looks like each individual file has its own access condition - but that's not how it works in METS. The access condition is _computed_ for each file, because in user interactions it has to be enforced atomically on files individually.
