### ISSUE TITLE
Set up and test S3 connection for regular and editorial photography workflows

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#4035]

**Comment by aray-wellcome** [comment]
Test for regular and EP workflows tested on AWS Goobi and were successful. Clarifying with Intranda about process title matching.

**Comment by aray-wellcome** [comment]
Have clarified, process title matching has to be exact. Due to some inconsistencies in title processing, we'll have some teething problems at the start to see what needs to be done. Might a combination of changing existing titles in Goobi and/or working with Branwen to get more consistent metadata into Goobi process titles.
