### ISSUE TITLE
Allow storage-service to provide METS notifications to other services

### ISSUE THREAD

**Issue by warrd** [wellcometrust/platform#4045]
The mets adaptor will need to know when there are new METS files / updates, so storage-service will need to publish to a topic for this purpose.

**Comment by alexwlchan** [comment]
Taking out of the board for now; will discuss at planning this afternoon.

**Comment by alexwlchan** [comment]
So it turns out we already have an SNS topic that's providing this information in the storage service (sort of).

Specifically, `storage_prod_bag_register_output` spits out the pipeline message it received. Here's what a message looks like:

```json
{
  "context": {
    "ingestId": "33e64141-b8ef-4ec5-98c7-20b1ac3c2e74",
    "ingestType": {
      "id": "create"
    },
    "storageSpace": "digitised",
    "ingestDate": "2019-11-24T12:27:06.462720Z",
    "externalIdentifier": "b18423383"
  },
  "version": 1,
  "knownReplicas": {
    "location": {
      "provider": {
        "type": "InfrequentAccessStorageProvider"
      },
      "prefix": {
        "namespace": "wellcomecollection-storage",
        "path": "digitised/b18423383/v1"
      }
    },
    "replicas": [
      {
        "provider": {
          "type": "GlacierStorageProvider"
        },
        "prefix": {
          "namespace": "wellcomecollection-storage-replica-ireland",
          "path": "digitised/b18423383/v1"
        }
      }
    ]
  },
  "type": "KnownReplicasPayload"
}
```

The `"knownReplicas"` block is storage service only and can be ignored; the `"context"` and `"version"` have what I think you need for the catalogue. If we set up cross-account SNS access that could work.
