### ISSUE TITLE
Store Archivematica packages with human-readable IDs

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#4084]
Currently we store Archivematica packages in the storage service as UUIDs. Yuck!

<img width="760" alt="Screenshot 2019-11-29 at 06 37 21" src="https://user-images.githubusercontent.com/301220/69848721-bc1fe500-1272-11ea-9e4e-dbd803162cbc.png">

One of the nice things about the digitised content is that it's laid out in a much more human-readable way. If all you had was the S3 files, you could get pretty far:

<img width="653" alt="Screenshot 2019-11-29 at 06 37 47" src="https://user-images.githubusercontent.com/301220/69848761-d3f76900-1272-11ea-93b9-92eca8ffdbcb.png">

Wouldn't it be neat if we could do this for the born-digital content?

**Comment by alexwlchan** [comment]
This works “well enough”. It needs proper testing and review, but Helen is focusing on Artefactual PRs so we can get stuff in before the Christmas change freeze.

One thing we should tweak is how it does prefixes, currently “PPABC/123” and “PPABC/145” would get the common prefix “PPABC/1”, really it should be “PPABC/”.

**Comment by alexwlchan** [comment]
Remember to strip slashes! The storage service rejects external identifiers that end in a slash, so it should actually be `PPABC`.

**Comment by alexwlchan** [comment]
Jonathan has (fairly) pointed out that using `metadata.csv` isn't good enough, because you can populate data in the Archivematica user interface! Thus, a revised proposal:

1. Look in the METS for `dc.identifier` values. Pick a common prefix if possible (e.g. if we have `LE/MON/1` and `LE/MON/2`, we’d use `LE/MON`).
2. If there are no instances of `dc.identifier`, look for an accession detail in the METS, i.e.:

    ```xml
    <premis:eventOutcomeDetailNote>accession#LEMON</premis:eventOutcomeDetailNote>
    ```

    As with (1), we look for all values and pick a common prefix if possible.
3. If we can't find a `dc.identifier` or an accession detail, use the package UUID.

**Comment by ross-spencer** [comment]
I'm not following the entire conversation here, i.e. where metadata.csv falls short because of the UI. Just reflecting, an alternative method of growing popularity for creating new identifiers for packages and content is our identifiers.json sidecar which ends up as a `PREMIS:objectIdentifier`.

* [Docs](https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/transfer/transfer/#transfers-with-existing-persistent-identifiers).
* [Sample file and transfer](https://github.com/artefactual/archivematica-sampledata/blob/6e299d0c43e3ccc19f6eb1132a7b04b70e300866/SampleTransfers/DemoTransferCSV/metadata/identifiers.json).

This will soon be searchable in the UI via Elasticsearch where the first iteration focused on making sure the identifiers wound up in the METS correctly.

**Comment by alexwlchan** [comment]
@ross-spencer Sorry, this is missing some context that happened outside GitHub!

My original implementation for this was just to read the `dc.identifier` value from the `metadata.csv` file – but you can also populate that metadata through the Archivematica UI, AIUI? So if the metadata file is empty but you've added metadata in the UI, that wouldn't be picked up by my code that just reads the CSV.

The `identifiers.json` is interesting and new to me – and might be exactly what we need. Thanks for the pointer!

**Comment by ross-spencer** [comment]
@alexwlchan I see! thanks for following-up. If I read back correctly now then yep, the AIP METS is a pretty good bet for this. I hope too the identifiers.json might work out quite nicely for y'all. It is proving to create a bit of flexibility for folk who want to do things with IDs.
