### ISSUE TITLE
Issues with thumbnails from METS

### ISSUE THREAD

**Issue by alicefuzier** [wellcometrust/platform#4146]
- [x] https://api-stage.wellcomecollection.org/catalogue/v2/works/a7w6e6gz?include=identifiers,items
The thumbnail path should be https://dlcs.io/thumbs/wellcome/5/B18252710_0001.jp2/full/!200,200/0/default.jpg ie without prepending the lowercase bnumber as it's already beginning with a bnumber. Checking if it starts with a bnumber should be case insensitive
 - [ ] https://api.wellcomecollection.org/catalogue/v2/works/keqceg6b?include=items,identifiers 
is a video so it doesn't have a thumbnail. However it does have a posterimage: https://wellcomelibrary.org/posterimages/b20168627/0055-0000-7095-0000-0-0000-0000-0.jpg
 - [ ] https://api-stage.wellcomecollection.org/catalogue/v2/works/dy2vwk6z?include=items,identifiers,notes 
PDF thumbnails, as for videos, are served by wellcomelibrary: `https://wellcomelibrary.org/pdfthumbs/<b-number>/0/<asset-id>.jpg` where asset-id in this case is `b28897857_response-nutrition-labelling-consultation.pdf`
- [x] minor: change `https://dlcs.io/iiif-img/wellcome/5/${filename}/full/!200,200/0/default.jpg` to `https://dlcs.io/thumbs/wellcome/5/${filename}/full/!200,200/0/default.jpg` ie replace /iiif-img/ with /thumbs/

**Comment by tomcrane** [comment]
Minor suggestion - use the /thumbs/ path:

 https://dlcs.io/iiif-img/.... =>  https://dlcs.io/thumbs/

Although this will result in the same image as the thumb service, it makes it easier to optimise thumb delivery later. On /iiif-img/ the DLCS recognises that the requested size and format can be served by an already-made image rather than forwarding to an image server, so it's still optimised, but using the explicit path allows a different service to handle it in future.

**Comment by alicefuzier** [comment]
Thanks @tomcrane I updated the ticket
