### ISSUE TITLE
PDF on the library website is displaying the wrong images

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#4158]
A reader has written in to point out an issue with the PDFs on this book: https://wellcomelibrary.org/item/b29334123

If you download (say) volume 3, you get the images from volume 4 (see title page: “Volume IV”).

I flagged this to Tom Crane, who pointed me at <http://wt-havana:85/Dash/Manifestation/b29334123_0001>. If we click “Delete PDF”, that will delete the cached PDF, and it'll be rebuilt the next time somebody requests it. Unfortunately, clicking that button throws a 400 Bad Request error and a stack trace. Tom is going to investigate what's going on in the dashboard.

- [x] Fix the borken PDFs
- [x] Let reader know they can download the PDFs they want
- [x] Document the process of clearing the PDF cache, so we know how to resolve this in future without having to ask Tom

**Comment by pollecuttn** [comment]
v1 PDF downloads fine in UV
v2 PDF downloads fine in UV
v3 PDF downloads in UV but it's v4
v4 PDF downloads in UV but it's v5
v5 cannot download PDF in UV (but can download it by selecting v4)
v6 cannot download PDF in UV
v7 cannot download PDF in UV
v8 cannot download PDF in UV

So you can download PDFs of vols 1, 2, 4, 5.
You cannot download PDFs of vols 3, 6, 7, 8

**Comment by tomcrane** [comment]
@pollecuttn @alexwlchan the PDFs for this item are now working.

PDFs are generated by querying the image-associated metadata, which includes properties that we use for bnumber, manifestation, and order. 

So you can ask DLCS to generate a PDF from a query, where s1=bnumber and n1=manifestation and order by n2, and pull a cover page from _this_ parameterisable URL.

Once created, a PDF is stored in S3 along with a control file, and if the control file is good, the DLCS will serve up the S3 PDF.

That's all great... but post migration, we have images with the same metadata but different IDs in different spaces, and we weren't dealing with that properly. Some reconfiguration and the PDFs above look good.

When you delete a PDF from the dashboard, you delete the control file, so the DLCS remakes the PDF when next asked for it. PDFs don't get deleted very often, and a bug had been introduced to this operation.  While the PDF issue was fixed with configuration changes, the delete issue requires a redeploy, which we'll do this afternoon.

**Comment by alexwlchan** [comment]
Woohoo! Thanks Tom. I’m not back in the office until Tuesday; when I am I’ll scribble a few notes on how we fix this next time and get some screenshots from wt-havana.

**Comment by aray-wellcome** [comment]
Happened to need to delete a PDF (a rare thing) today so I took some screenshots.

b30303989 was ingested from IA and IA gave us corrupted images. All images were blank gray. I re-ingested them after IA fixed them. Downloading the PDF after I harvested the new items, the PDF still showed the gray images. 

This items's PDF had been requested by a reader on the 3rd of Feb so it showed that date. 
![image](https://user-images.githubusercontent.com/49983203/73918807-3b0c4c00-48ba-11ea-85e0-b8ebda84fbc2.png)

I clicked the Deleted PDF button and when the page refreshed, the PDF was waiting to be remade:
![image](https://user-images.githubusercontent.com/49983203/73918875-6000bf00-48ba-11ea-8edb-eb140c7ab023.png)

I clicked Make PDF and it created it with today's timestamp:
![image](https://user-images.githubusercontent.com/49983203/73918920-73138f00-48ba-11ea-97bd-93410ad5fe10.png)

And then I went to https://wellcomelibrary.org/item/b30303989?ts=637165741321373533 and downloaded the PDF option and the PDF was showing the correct page images. 

So I can confirm the Delete PDF button bug is resolved. And I hope these screenshots help tick off the last box of this ticket!
